Change `devnet.yml` to be composite action

diff --git a/.github/workflows/devnet.yml b/.github/workflows/devnet.yml
--- a/.github/workflows/devnet.yml
+++ b/.github/workflows/devnet.yml
@@ -1,55 +1,50 @@
-name: Devnet setup
+name: "Devnet Setup"
+description: "Set up starknet-devnet locally for tests"
+runs:
+  using: "composite"
+  steps:
+    - name: Checkout repository
+      uses: actions/checkout@v4
+      with:
+        submodules: recursive
 
-env:
-  DEVNET_SHA: dd559716849ade47cc06be150edf250e5dccb2bf
+    - name: Clone starknet-devnet-rs
+      run: |
+        DEVNET_SHA="dd559716849ade47cc06be150edf250e5dccb2bf"
+        git clone https://github.com/0xSpaceShard/starknet-devnet-rs.git starknet-devnet-rs
+        cd starknet-devnet-rs
+        git checkout "$DEVNET_SHA"
 
-on:
-  workflow_call:
+    - name: Cache devnet build
+      uses: actions/cache@v4
+      with:
+        path: starknet-devnet-rs/target/release
+        key: ${{ runner.os }}-starknet-devnet-rs-target-release-dd559716849ade47cc06be150edf250e5dccb2bf
 
-jobs:
-  setup-devnet:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          submodules: recursive
+    - name: Build and install devnet
+      shell: bash
+      run: |
+        DEVNET_INSTALL_DIR="$(git rev-parse --show-toplevel)/starknet_py/tests/e2e/devnet/bin"
+        mkdir -p "$DEVNET_INSTALL_DIR"
 
-      - name: Clone starknet-devnet-rs
-        run: |
-          git clone https://github.com/0xSpaceShard/starknet-devnet-rs.git starknet-devnet-rs
-          pushd ${{ github.workspace }}/starknet-devnet-rs
-          git checkout ${{ env.DEVNET_SHA }}
-          popd
+        if [[ ! -d starknet-devnet-rs/target/release ]]; then
+          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
+          export PATH="$HOME/.cargo/bin:$PATH"
+          
+          cd starknet-devnet-rs
+          cargo build --release
+          cp ./target/release/starknet-devnet "$DEVNET_INSTALL_DIR"
+        else
+          echo "Found existing starknet-devnet-rs build, skipping compilation."
+          cp starknet-devnet-rs/target/release/starknet-devnet "$DEVNET_INSTALL_DIR"
+        fi
 
-      - name: Cache devnet build
-        uses: actions/cache@v4
-        with:
-          path: starknet-devnet-rs/target/release
-          key: ${{ runner.os }}-starknet-devnet-rs-target-release-${{ env.DEVNET_SHA }}
-
-      - name: Build and Install devnet
-        run: |
-          DEVNET_INSTALL_DIR="$(git rev-parse --show-toplevel)/starknet_py/tests/e2e/devnet/bin"
-          mkdir -p "$DEVNET_INSTALL_DIR"
-
-          if [[ ! -d ${{ github.workspace }}/starknet-devnet-rs/target/release ]]; then
-            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
-            export PATH="$HOME/.cargo/bin:$PATH"
-            
-            pushd ${{ github.workspace }}/starknet-devnet-rs
-            cargo build --release
-            cp ./target/release/starknet-devnet "$DEVNET_INSTALL_DIR"
-            popd
-          else
-            echo "Found existing starknet-devnet-rs build, skipping compilation."
-            cp ${{ github.workspace }}/starknet-devnet-rs/target/release/starknet-devnet "$DEVNET_INSTALL_DIR"
-          fi
-
-      - name: Verify devnet installation
-        run: |
-          DEVNET_INSTALL_DIR="$(git rev-parse --show-toplevel)/starknet_py/tests/e2e/devnet/bin"
-          if [[ -x "$DEVNET_INSTALL_DIR/starknet-devnet" ]]; then
-            echo "starknet-devnet successfully installed at $DEVNET_INSTALL_DIR"
-          else
-            echo "starknet-devnet installation failed!" && exit 1
-          fi
+    - name: Verify devnet installation
+      shell: bash
+      run: |
+        DEVNET_INSTALL_DIR="$(git rev-parse --show-toplevel)/starknet_py/tests/e2e/devnet/bin"
+        if [[ -x "$DEVNET_INSTALL_DIR/starknet-devnet" ]]; then
+          echo "starknet-devnet successfully installed at $DEVNET_INSTALL_DIR"
+        else
+          echo "starknet-devnet installation failed!" && exit 1
+        fi
